QEMU_CONN = "qemu:///system"

P_DOMAIN_XML = "domain_xml"
P_DOMAIN_NAME = "domain_name"
P_DOMAIN_UUID = "domain_uuid"
P_NEW_NAME = "new_name"
P_NEW_DESCRIPTION = "new_description"
P_DOMAINS_NAME_LIST = "domains_name_list"
P_CPU_NUM = "cpu_num"
P_MEMORY_SIZE = "memory_size"

P_CHILD_NAME = "child_name"

P_NETWORK_ADDRESS = "network_address"
P_BRIDGE_NAME = "bridge_name"
P_PORT_NAME = "port_name"
P_TYPE = "type"
P_REMOTE_IP = "remote_ip"
P_TAG = "tag"
P_NETWORKA = "networkA"
P_NETWORKB = "networkB"
P_INTERFACE_NAME = "interface_name"
P_INTERFACE_NAMES = "interface_names"
P_GATEWAY = "gateway"
P_GATEWAYS = "gateways"

P_PARENT = "parent"

P_DEVICE_XML = "device_xml"
P_FLAGS = "flags"
P_USER_NAME = "user_name"
P_PASSWD = "passwd"

P_IP_ADDRESS = "ip_address"
P_IP_ADDRESSES = "ip_addresses"

P_CONTAINER_ID = "container_id"
P_IMAGE = "image"
P_PORTS = "ports"
P_DETACH = "detach"
P_CONTAINER_NAME = "container_name"
P_NETWORK_NAME = "network_name"
P_CPU_SHARES = "cpu_shares"

P_SWARM_WORKER_TOKEN = "swarm_worker_token"
P_SWARM_MANAGER_TOKEN = "swarm_manager_token"
P_REMOTE_ADDRS = "remote_addrs"
P_ADVERTISE_ADDR = "advertise_addr"
P_LISTEN_ADDR = "listen_addr"
P_FORCE = "force"