P_SLAVE_NAME = "slave_name"
P_DOMAIN_NAME = "domain_name"
P_NEW_NAME = "new_name"
P_NEW_DESCRIPTION = "new_description"
P_DOMAIN_UUID = "domain_uuid"
P_DOMAINS_NAME_LIST = "domains_name_list"
P_DOMAIN_XML = "domain_xml"
P_CPU_NUM = "cpu_num"
P_MEMORY_SIZE = "memory_size"

P_CHILD_NAME = "child_name"

P_NETWORK_ADDRESS = "ip_address"
P_NETWORK_NAME = "network_name"
P_IP_ADDRESS = "network_address"
P_BRIDGE_NAME = "bridge_name"
P_PORT_NAME = "port_name"
P_TYPE = "type"
P_REMOTE_IP = "remote_ip"
P_TAG = "tag"
P_NETWORKA = "networkA"
P_NETWORKB = "networkB"
P_INTERFACE_NAME = "interface_name"
P_GATEWAY = "gateway"
P_MAC = "mac"

P_PARENT = "parent"

P_DEVICE_XML = "device_xml"
P_PORT = "port"
P_PASSWD = "passwd"
P_FLAGS = "flags"